In [0]:
import numpy as np

Function to check whether numpy array has Zero values or not

In [0]:
def chkZeros(arr):
  if 0 in arr:
    return True
  else:
    return False
  
  
arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr2 = np.arange(10)

print(f'is there a zero in arr1 : {chkZeros(arr1)}')
print(f'is there a zero in arr2 : {chkZeros(arr2)}')

is there a zero in arr1 : False
is there a zero in arr2 : True


Consider an array contains marks of students. Find the median and mean of students who got passing marks.

In [0]:
def medMean(arr):
  l = []
  for i in arr:
    if i >= 40:
      l.append(i)
  l = np.array(l)
  
  med = np.median(l)
  mean = l.mean()
  
  print(f'Median of students who got passing marks = {med}')
  print(f'Mean of students who got passing marks = {mean}')
  
arr1 = np.array([42,52,72,30,92,85,74,62,55,43])
medMean(arr1)

Median of students who got passing marks = 62.0
Mean of students who got passing marks = 64.11111111111111


Consider an array containing date of birth of students (Use np.datetime64('2018-02-01')). Find the age of all students. If age is 18 label it First, if it is 19, label it Second, if it is 20, label it Third, if it is 21, label it Fourth.

In [0]:
def getLabel(temp):
  l = {18 : 'First', 19 : 'Second', 20 : 'Third', 21 : 'Fourth'}
  return l[temp]
  
def labelAge(dob):
  label = {}
  curDate = np.datetime64('2019-04-09')
  age = np.array((curDate - dob)/365, dtype = int)
  for a in range(7): 
    lable = label.update({dob[a] : getLabel(age[a])})
  for l in label:
    print(f'{l} : {label[l]}')
    
  
dob = ['1998-08-25','1998-09-09','1999-01-22','1999-03-10','1999-12-17','2000-12-05','1998-04-09']
dob = np.array(dob, dtype = 'datetime64')
labelAge(dob)

1998-08-25 : Third
1998-09-09 : Third
1999-01-22 : Third
1999-03-10 : Third
1999-12-17 : Second
2000-12-05 : First
1998-04-09 : Fourth


Create a function to sort 2d Array by a column.

In [23]:
def sort(arr,dim):
  l = []
  for i in arr:
    l = l + i.tolist()
  l = np.array(l)
  l.sort()
  l = l.reshape((dim,dim))
  print(f'Sorted array : ')
  print(l)
  
arr = np.array([[2,1,4],[3,6,5],[8,9,7]])
print(f'Given array : ')
print(arr)
sort(arr,3)

Given array : 
[[2 1 4]
 [3 6 5]
 [8 9 7]]
Sorted array : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Create one hot encoding of an array.

In [36]:
def hotEncoding(arr):
  Max = arr.max()
  (x,) = arr.shape
  a = np.zeros((x,Max))
  for i in range(x):
    a[i][arr[i] - 1] = 1
  print(f'one hot encoding of the given array : ')
  print(a)
  
arr = np.array([2, 3, 2, 2, 2, 1])
hotEncoding(arr)

one hot encoding of the given array : 
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


Drop all missing values (i.e, nan values) from an array Input

In [45]:
def delNAN(arr):
  print(f'Given array : {arr}')
  arr = arr.tolist()
  for i in arr:
    if np.isnan(i):
      arr.remove(i)
  arr = np.array(arr)
  print(f'Array after NAN removal : {arr}')
  
arr = np.array([1,2,3,np.nan,5,6,7,np.nan])
delNAN(arr)

Given array : [ 1.  2.  3. nan  5.  6.  7. nan]
Array after NAN removal : [1. 2. 3. 5. 6. 7.]


Find Local maxima from an array.

In [50]:
def Maxima(arr):
  (x,) = arr.shape
  maxima = []
  for i in range(x):
    if i == 0:
      if arr[i] > arr[i + 1]:
        maxima.append(i)
    elif i == (x - 1):
      if arr[i] > arr[i - 1]:
        maxima.append(i)
    else:
      if arr[i - 1] < arr[i] > arr[i + 1]:
        maxima.append(i)
  maxima = np.array(maxima)
  print(f'Local maximas indexes : {maxima}')
  
  
arr = np.array([1, 3, 7, 1, 2, 6, 0, 1])
Maxima(arr)

Local maximas indexes : [2 5 7]


From the given 1d array arr, generate a 2d matrix using strides:
For example for an array ([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])with a window length of w=4 and strides of s=2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..].
Also w and s will be provided by user

In [42]:
def genrate(arr,w,s):
  (x,) = arr.shape
  new_arr = []
  for i in range(0, (x - w + 1), s):
    end = i + w
    new_arr.append(arr[i:end])
  new_arr = np.array(new_arr, dtype = "int64")
  print(new_arr)


w = int(input('Enter the Window length : '))
s = int(input('Enter the Strides : '))
arr = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
genrate(arr,w,s)

Enter the Window length : 4
Enter the Strides : 2
[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]
